Env setup via asdf; dedockerize build; CI conf: asdf, fix PG10, asdf Firefox

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,27 +1,21 @@
 #!/usr/bin/env bash
-set -eu
+set -euo pipefail
 
 ### VARIABLES and PWD #########################################################
-
-set -x
 
 PROJECT_NAME="leihs-procure"
 
 PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd .. > /dev/null 2>&1 && pwd -P)"
-UI_DIR="${PROJECT_DIR}/client/leihs-ui"
+
+SERVER_DIR=${PROJECT_DIR}/server
+CLIENT_DIR=${PROJECT_DIR}/client
+UI_DIR="${CLIENT_DIR}/leihs-ui"
+
 ARTEFACT_PATH="$PROJECT_DIR/server/target/$PROJECT_NAME.jar"
 DIGEST="$(git -C "$PROJECT_DIR" log -n 1 HEAD --pretty=%T)"
 LOCAL_CACHE_DIR="${LOCAL_CACHE_DIR:-"${TMPDIR:-/tmp/}/leihs-build-cache"}"
 LOCAL_CACHED_ARTEFACT_PATH="${LOCAL_CACHE_DIR}/${PROJECT_NAME}_${DIGEST}.jar"
-S3_CACHED_ARTEFACT_NAME="${PROJECT_NAME}_${DIGEST}.jar"
 BUILD_CACHE_DISABLED="${BUILD_CACHE_DISABLED:-NO}"
-USE_DOCKER="${USE_DOCKER:-YES}"
-FORCE_DOCKER_BUILD="${FORCE_DOCKER_BUILD:-NO}"
-
-# add our clojure version to the path
-source $PROJECT_DIR/server/shared-clj/clojure/bin/activate
-
-set +x
 
 cd "${PROJECT_DIR}"
 echo "PWD: $PWD"
@@ -34,24 +28,13 @@ else
   exit 1
 fi
 
-if [ $USE_DOCKER == "YES" ] ||  [ $USE_DOCKER == "NO" ]; then
-  echo "USE_DOCKER=$USE_DOCKER"
-else
-  echo 'USE_DOCKER must be initially unset, or "YES", or "NO"'
-  exit 1
-fi
-
 
 ### functions #################################################################
 
 function build {
-  if [ $USE_DOCKER == "YES" ]; then
-    bin/docker-build
-  else
-    ${UI_DIR}/bin/build || { echo "UI build error!"; exit 1; }
-    ${CLIENT_DIR}/bin/build || { echo "CLIENT build error!"; exit 1; }
-    ${SERVER_DIR}/bin/clj-uberjar || { echo "CLIENT uberjar error!"; exit 1; }
-  fi
+  ${UI_DIR}/bin/build || { echo "UI build error!"; exit 1; }
+  ${CLIENT_DIR}/bin/build || { echo "CLIENT build error!"; exit 1; }
+  ${SERVER_DIR}/bin/clj-uberjar || { echo "CLIENT uberjar error!"; exit 1; }
 }
 
 function pack {
@@ -67,37 +50,19 @@ function extract {
 ### MAIN ######################################################################
 
 if [ $BUILD_CACHE_DISABLED == "YES" ]; then
-
   echo "INFO: BUILD_CACHE_DISABLED is YES, building and nothing else"
   build
-
 else
-
-  source ${UI_DIR}/bin/require-clean-working-tree
+  source ${UI_DIR}/bin/require-clean-working-tree.sh
   require-clean-working-tree
-
   echo "LOCAL_CACHED_ARTEFACT_PATH: $LOCAL_CACHED_ARTEFACT_PATH"
 
   if [ -e $LOCAL_CACHED_ARTEFACT_PATH ]; then
-
     echo "INFO: locally cached artefact found, extracting, and caching ..."
     extract
-
-    ${UI_DIR}/bin/s3-cache-helper upload -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
   else
-
-    echo "S3_CACHED_ARTEFACT_NAME: $S3_CACHED_ARTEFACT_NAME"
-    echo "INFO: trying to download from S3 cache"
-    ${UI_DIR}/bin/s3-cache-helper download -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
-    if [ -e $LOCAL_CACHED_ARTEFACT_PATH ]; then
-      echo "INFO: artefact found, extracting "
-      extract
-    else
-      echo "INFO: no cached artefact found: building, packing, and caching ..."
-      build
-      pack
-      ${UI_DIR}/bin/s3-cache-helper upload -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
-    fi
+    build
+    pack
   fi
 fi
 
