extend build caching

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -euo
+set -eu
 
 ### VARIABLES and PWD #########################################################
 
@@ -9,13 +9,13 @@ set -x
 PROJECT_NAME="leihs-procure"
 
 PROJECT_DIR="$(realpath $(dirname ${BASH_SOURCE})/..)"
-CLIEND_DIR="${PROJECT_DIR}/client"
-UI_DIR="${PROJECT_DIR}/client/leihs-ui"
+CLIENT_DIR="${PROJECT_DIR}/client/"
+UI_DIR="${CLIENT_DIR}/leihs-ui"
 ARTEFACT_PATH="$PROJECT_DIR/server/target/$PROJECT_NAME.jar"
-DIGEST="$(git log -n 1 HEAD --pretty=%T)"
-TMPDIR="${TMPDIR:-/tmp/}"
-LOCAL_CACHED_ARTEFACT_PATH="${TMPDIR}${PROJECT_NAME}_${DIGEST}.jar"
-S3_CACHED_ARTEFACT_NAME="${PROJECT_NAME}_${DIGEST}.tgz"
+DIGEST="$(git -C "$PROJECT_DIR" log -n 1 HEAD --pretty=%T)"
+LOCAL_CACHE_DIR="$(realpath -m "${LOCAL_CACHE_DIR:-"${TMPDIR:-/tmp/}/leihs-build-cache"}")"
+LOCAL_CACHED_ARTEFACT_PATH="${LOCAL_CACHE_DIR}/${PROJECT_NAME}_${DIGEST}.jar"
+S3_CACHED_ARTEFACT_NAME="${PROJECT_NAME}_${DIGEST}.jar"
 BUILD_CACHE_DISABLED="${BUILD_CACHE_DISABLED:-NO}"
 
 set +x
@@ -25,6 +25,7 @@ echo "PWD: $PWD"
 
 if [ $BUILD_CACHE_DISABLED == "YES" ] ||  [ $BUILD_CACHE_DISABLED == "NO" ]; then
   echo "BUILD_CACHE_DISABLED=$BUILD_CACHE_DISABLED"
+  mkdir -p "$LOCAL_CACHE_DIR"
 else
   echo 'BUILD_CACHE_DISABLED must be initially unset, or "YES", or "NO"'
   exit 1
@@ -33,15 +34,21 @@ fi
 
 ### functions #################################################################
 
+
+
 function build {
-  ${UI_DIR}/bin/build
-  ${CLIEND_DIR}/bin/build
+  ${UI_DIR}/bin/build || { echo "UI build error!"; exit 1; }
+  ${CLIENT_DIR}/bin/build || { echo "CLIENT build error!"; exit 1; }
   cd server
-  LEIN_SNAPSHOTS_IN_RELEASE=LOL lein do uberjar || { echo "build error!"; exit 1; }
+  LEIN_SNAPSHOTS_IN_RELEASE=LOL lein do uberjar || { echo "SERVER build error!"; exit 1; }
   cd -
 }
 
-function copy_locally_cached_artefact {
+function pack {
+  cp "$ARTEFACT_PATH" "$LOCAL_CACHED_ARTEFACT_PATH"
+}
+
+function extract {
   mkdir -p $(dirname $ARTEFACT_PATH)
   cp "$LOCAL_CACHED_ARTEFACT_PATH" "$ARTEFACT_PATH"
 }
@@ -59,33 +66,39 @@ else
   source ${UI_DIR}/bin/require-clean-working-tree
   require-clean-working-tree
 
+  # RUBY on CI for ${UI_DIR}/bin/s3-cache-helper
+  RUBY="${RUBY:-EMPTY}"
+  if [ "${RUBY}" != 'EMPTY' ]; then
+    export PATH=~/.rubies/$RUBY/bin:$PATH
+  fi
+
+  echo "LOCAL_CACHED_ARTEFACT_PATH: $LOCAL_CACHED_ARTEFACT_PATH"
+
   if [ -e $LOCAL_CACHED_ARTEFACT_PATH ]; then
 
-    echo "INFO: locally cached artefact found, copying "
-    copy_locally_cached_artefact
+    echo "INFO: locally cached artefact found, extracting, and caching ..."
+    extract
 
+    ${UI_DIR}/bin/s3-cache-helper upload -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
   else
 
-    # RUBY on CI for ${UI_DIR}/bin/s3-cache-helper
-    RUBY="${RUBY:-EMPTY}"
-    if [ "${RUBY}" != 'EMPTY' ]; then
-      export PATH=~/.rubies/$RUBY/bin:$PATH
-    fi
-
-    echo "INFO: trying to download $S3_CACHED_ARTEFACT_NAME from S3 cache"
+    echo "S3_CACHED_ARTEFACT_NAME: $S3_CACHED_ARTEFACT_NAME"
+    echo "INFO: trying to download from S3 cache"
     ${UI_DIR}/bin/s3-cache-helper download -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
     if [ -e $LOCAL_CACHED_ARTEFACT_PATH ]; then
-      echo "INFO: artefact found, copying"
-      copy_locally_cached_artefact
+      echo "INFO: artefact found, extracting "
+      extract
     else
-      echo "INFO: no cached artefact found: building and caching ..."
+      echo "INFO: no cached artefact found: building, packing, and caching ..."
       build
-      cp "$ARTEFACT_PATH" "$LOCAL_CACHED_ARTEFACT_PATH"
+      pack
       ${UI_DIR}/bin/s3-cache-helper upload -n "$S3_CACHED_ARTEFACT_NAME" -p "$LOCAL_CACHED_ARTEFACT_PATH"
     fi
   fi
 fi
 
 cd -
+
+echo "OK ✔"
 
 # vi: ft=sh
