ci: build fixes
backported from deploy

diff --git a/cider-ci/ui_task_component.yml b/cider-ci/ui_task_component.yml
--- a/cider-ci/ui_task_component.yml
+++ b/cider-ci/ui_task_component.yml
@@ -37,7 +37,7 @@ scripts:
         s3-cache-helper download -n "$S3_CACHED_ARTEFACT" -p "$LOCAL_CACHED_ARTEFACT"
         # build the artefact if it was not downloaded
         if [ ! -f ${LOCAL_CACHED_ARTEFACT} ]; then
-          ./scripts/prepare-shared-ui.sh
+          ./scripts/prepare-shared-ui.sh || { echo "build error!"; exit 1; }
           tar -cvz -f "$LOCAL_CACHED_ARTEFACT" $ARTEFACT_PATHS
           s3-cache-helper upload -n "$S3_CACHED_ARTEFACT" -p "$LOCAL_CACHED_ARTEFACT"
         fi
